# _config.yml
title: Java Blog
description: Un blog de apoyo para aprender a programar en JAVA
baseurl: "/Java-Blog"  # Si tu sitio está en el dominio raíz (ej. https://misitio.com), déjalo vacío
url: "http://unciafidelis.github.io"  # Tu dominio principal, por ejemplo, https://misitio.com
markdown: kramdown

# Opcional: si quieres que los posts tengan un formato de URL específico
# Aquí se utiliza un formato que genera URLs amigables
permalink: /:year/:month/:day/:title.html

# Otras configuraciones personalizadas
include:
  - styles.css
